-- VortexSoft Title Services LLC — MySQL Database Schema
-- Run this file once on Hostinger MySQL via phpMyAdmin
-- Database: (your Hostinger DB name)

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

-- --------------------------------------------------------
-- Table: vts_admins
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS `vts_admins` (
  `id`          INT(11) NOT NULL AUTO_INCREMENT,
  `name`        VARCHAR(100) NOT NULL,
  `email`       VARCHAR(150) NOT NULL,
  `password`    VARCHAR(255) NOT NULL COMMENT 'bcrypt hash',
  `role`        ENUM('superadmin','admin') NOT NULL DEFAULT 'admin',
  `last_login`  DATETIME DEFAULT NULL,
  `created_at`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Seed: Super Admin — admin@vortexsofttitles.com / Mrunal@9996
-- Seed: Admin — Aniket@vortexsofttitles.com / ShivaG@1437
INSERT INTO `vts_admins` (`name`, `email`, `password`, `role`) VALUES
('Super Admin', 'admin@vortexsofttitles.com', '$2y$12$J7eMfMIlw1b5DPwuY0x1Y.H8L5zqKFf7gV6hHIa.hHmk9KFNS9/Hu', 'superadmin'),
('Aniket', 'Aniket@vortexsofttitles.com', '$2y$12$Qb5Zp3YkHmXI4v.4jE2XHuKRU2ZqKDMYFhYz2.LS0.Z5rNdFYqJ1a', 'admin');
-- NOTE: These are placeholder hashes. The actual hashes are generated by install.php

-- --------------------------------------------------------
-- Table: vts_contacts
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS `vts_contacts` (
  `id`          INT(11) NOT NULL AUTO_INCREMENT,
  `name`        VARCHAR(100) NOT NULL,
  `email`       VARCHAR(150) NOT NULL,
  `phone`       VARCHAR(30) DEFAULT NULL,
  `subject`     VARCHAR(200) DEFAULT NULL,
  `message`     TEXT NOT NULL,
  `ip_address`  VARCHAR(45) DEFAULT NULL,
  `is_read`     TINYINT(1) NOT NULL DEFAULT 0,
  `created_at`  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_is_read` (`is_read`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------
-- Table: vts_newsletter
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS `vts_newsletter` (
  `id`              INT(11) NOT NULL AUTO_INCREMENT,
  `email`           VARCHAR(150) NOT NULL,
  `name`            VARCHAR(100) DEFAULT NULL,
  `is_active`       TINYINT(1) NOT NULL DEFAULT 1,
  `subscribed_at`   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------
-- Table: vts_settings
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS `vts_settings` (
  `id`            INT(11) NOT NULL AUTO_INCREMENT,
  `setting_key`   VARCHAR(100) NOT NULL,
  `setting_value` TEXT DEFAULT NULL,
  `updated_at`    TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `setting_key` (`setting_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Default site settings
INSERT INTO `vts_settings` (`setting_key`, `setting_value`) VALUES
('site_title',        'VortexSoft Title Services LLC'),
('site_tagline',      'Precision. Speed. Trust.'),
('site_email',        'Contact@vortexsofttitles.com'),
('site_phone',        '1-307-205-0681'),
('site_address_us',   '30 N Gould St Ste 100, Sheridan, WY 82801'),
('site_address_in',   'No.125, Ranganath Complex, Madiwala, HSR Layout 5th Sector, Bengaluru 560068'),
('meta_description',  'VortexSoft Title Services delivers speed, accuracy, and scale for Title Companies and Lenders across all 50 states. 24/7 Global Operations.'),
('smtp_host',         'mail.vortexsofttitles.com'),
('smtp_port',         '465'),
('smtp_user',         'Contact@vortexsofttitles.com'),
('smtp_pass',         'CHANGE_ME_HOSTINGER_SMTP_PASS'),
('smtp_from_name',    'VortexSoft Title Services'),
('google_analytics',  '');
